name: 'yuque to readme'
description: 'Easily embed contents of yuque.com into README.md.'
branding:
  icon: 'book'
  color: 'green'
inputs:
  yuque-token: # token of yuque
    description: 'secrets.YUQUE_TOKEN. 语雀的 token，去 https://www.yuque.com/settings/tokens 里找。需要读取你的知识库和文档。'
    required: true
    default: 'secrets.YUQUE_TOKEN'
  yuque-namespace:
    description: '填你自己的空间标识。比如语雀的博客是： `yuque/blog`'
    required: true
    default: 'yuque/blog'
  yuque-doc-public-only:
    description: '是否只列出已发布的文章'
    default: true
  yuque-doc-limit:
    description: '最多列出几条'
    default: 5
  yuque-doc-order-by:
    description: '按什么字段排序'
    default: 'updated_at'
  yuque-template-file:
    description: 'Template for generate output'
    default: 'README.template.md'
  yuque-output-file:
    description: 'Which file to write'
    default: 'README.md'
runs:
  using: 'node12'
  main: 'dist/index.js'
