on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          yuque-token: ${{secrets.YUQUE_TOKEN}}
          yuque-namespace: 'luchen/buzhou'
          yuque-output-file: README.output.md
          yuque-record-template: '- [{{title}} ({{short createdAt format="MMMM dd, YYYY"}})](https://yuque.com/{{namespace}}/{{slug}})'
      - name: Result
        run: |-
          cat README.md
      - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
